# Generated by Django 4.2.4 on 2023-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appentrega', '0004_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='catedra',
            field=models.ManyToManyField(to='Appentrega.catedra'),
        ),
    ]
