# Generated by Django 4.2.4 on 2023-09-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appentrega', '0005_profesor_catedra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='nnombre',
            new_name='nombre',
        ),
    ]
